# CLA Assistant Configuration
# This file configures the CLA Assistant GitHub App
# Install the app from: https://github.com/apps/cla-assistant

# Path to the Contributor Assignment Agreement document
claDocumentPath: "CONTRIBUTOR_ASSIGNMENT.md"

# Path where signed Contributor Assignment Agreements are stored (in a separate repository or branch)
# You can use a separate repository for storing signatures
# signaturesPath: "cla-signatures"

# Whether to allow contributors to sign on behalf of their organization
allowListPattern: ".*"

# Whether to require re-signing when Contributor Assignment Agreement is updated
requireReSigningOnUpdate: false

# Custom message to show when Contributor Assignment Agreement is not signed
customPrSignComment: |
  Thank you for your pull request! 
  
  Before we can review your contribution, you need to sign our Contributor Assignment Agreement.
  
  Please read the [CONTRIBUTOR_ASSIGNMENT.md](CONTRIBUTOR_ASSIGNMENT.md) document and sign it using the link below.
  
  Once you've signed the Contributor Assignment Agreement, this check will automatically pass and your PR will be ready for review.

# Message to show after Contributor Assignment Agreement is signed
signedComment: |
  ✅ Thank you for signing the Contributor Assignment Agreement! Your contribution is now ready for review.

# Message to show when Contributor Assignment Agreement check fails
unsignedComment: |
  ❌ The Contributor Assignment Agreement has not been signed yet. Please sign the Contributor Assignment Agreement to proceed.

